version: '2'
services:
    base-notebook:
        ports:
            - 10000:8888
        volumes:
            - /home/pi/notebooks:/notebooks
        build: .
        image: jupyter:latest
        privileged: true
        devices:
            - /dev/i2c-1:/dev/i2c-1
            - /dev/gpiomem:/dev/gpiomem
            - /dev/vchiq:/dev/vchiq
